### ISSUE TITLE
px-to-rem.px-per-rem setting is waiting for a integer, not a string

### ISSUE THREAD

**Issue by lucasriondel** [sainoba/vscode-px-to-rem#11]
It's not a BIG issue actually, but in the README you wrote: `px-to-rem.px-per-rem: number of pixels per rem. Default is 16px.`. 

But if you try to put a string like "15px", the following error occur of course: 
![image](https://user-images.githubusercontent.com/7773454/69609349-9784fc80-1029-11ea-8778-e385ec4e93ec.png)

It's not a big deal, but your README is inducing that the setting value is a string when it's an integer (I was fooled :<). Could you change that ? :)

(great extension btw. thanks a lot !)

**Comment by sainoba** [comment]
Hey @lucasriondel thanks for reaching out, this seems like a bad issue. I'll try to fix it this weekend.
Glad to hear you are enjoying the extension :smiley:

**Comment by sainoba** [comment]
I just updated the README.
