### ISSUE TITLE
Add keybinding config

### ISSUE THREAD

**Issue by JHethDev** [sainoba/vscode-px-to-rem#14]
Alt + Z is the VS Code default to toggle word wrap. It would be nice to either be able to change the keybinding or disable altogether.

**Comment by sainoba** [comment]
Hello JaySwaan, thanks for writing.
You can actually disable/change the keybinding.

Just go to File > Preferences > Keyboard Shortcuts

Then search for `px to rem` and right-click on the keybinding you want to change.
There you can delete it or change it.

I hope it helps.
