### ISSUE TITLE
Upload the extension on Open VSX

### ISSUE THREAD

**Issue by GoodM4ven** [sainoba/vscode-px-to-rem#18]
Hey there,

Would you kindly make the extension available on [VSX](https://open-vsx.org/), so we can download it in [VSCodium](https://vscodium.com/)?

Thanks.

**Comment by sainoba** [comment]
Hey there, sure. I just upload it there: https://open-vsx.org/extension/sainoba/px-to-rem

**Comment by GoodM4ven** [comment]
Thanks a bunch. It's still **unverified** though! Can you follow the [namespace](https://github.com/eclipse/openvsx/wiki/Namespace-Access) setup they have?

**Comment by sainoba** [comment]
Done 👌
