### ISSUE TITLE
How to change the default conversion value 

### ISSUE THREAD

**Issue by chenxxzhe** [sainoba/vscode-px-to-rem#4]

**Comment by sainoba** [comment]
Hey, thanks for the question. This is usually the default way of modifying your settings in Visual Studio Code:

It's done in 3 steps:
1. Go to **File > Preference > Settings**
2. Add `"px-to-rem.px-per-rem": 16` to the right side of the settings file
3. Change **16** to the number you want to use and then save

I hope you are enjoying the plugin :smiley:
