### ISSUE TITLE
I can't use it properly

### ISSUE THREAD

**Issue by nj-novice** [sainoba/vscode-px-to-rem#5]
hi
  I can't use it properly,Keybindings =>  Alt+Z

**Comment by nj-novice** [comment]
Notice：There were no values to transform

**Comment by nj-novice** [comment]
can you help me?

**Comment by sainoba** [comment]
Hi thanks for writing
can you copy the text you are trying to modify?
also, what version of the plugin are you using?

**Comment by nj-novice** [comment]
trying to modify text `.container{font-size:16px}`,and version is 1.2.3@last .When I press Alt+z,alert ,Notice：There were no values to transform,The plugin configuration is default.

**Comment by sainoba** [comment]
Hi, what portion of the text are you selecting when you press `Alt + z` ??

**Comment by nj-novice** [comment]
Thanks for your help, the selected text can be converted.It's my own problem

**Comment by sainoba** [comment]
Glad I could help. Thanks for using my extension.
