### ISSUE TITLE
Show the conversion in an intellisense style in real-time

### ISSUE THREAD

**Issue by pingshunhuangalex** [sainoba/vscode-px-to-rem#6]
Migrating from Atom, it would be great if this extension can suggest `1rem` when I type `16px` and vice versa instead of using a shortcut to apply the calculation on the selection.

If not, at least let the shortcut work at the end of the unit instead of having to select the entire value string. Thanks.

**Comment by onetrev** [comment]
I would actually say the latter is definitely what I would prefer. It's a slow down in my workflow for sure to have to type the value, then, select the value before converting it. If the extension could convert the value my cursor is on when I hit keybinding shortcut that would amazing!

**Comment by sainoba** [comment]
That's a cool suggestion, once I get some free time I'll start working on it ☺️

**Comment by sainoba** [comment]
Hi guys, I took some time to modify the plugin. It's now in version **1.2.4**
Now you shouldn't need to select the value to convert it. You just need to position de cursor next to the value or inside it.

Please give it a try and let me know if you find any issues.
Ps. Thanks for using my plugin :slightly_smiling_face:

**Comment by onetrev** [comment]
Very cool, thanks for getting around to this!!! The conversion works perfectly as you mentioned. But I did discover one issue...

When converting from px -> rem and my cursor is at the end of the line, ex: 50px(cursor) then after the conversion some of the value ends up as selected text. As such, if I type anything without hitting the arrow keys first, the selected text gets erased. Hopefully that makes sense. 

Also, as it may be related to fixing this, ideally it would work such that the cursor after conversion is at the end of the value so you can just type a semi-colon and move on with your coding.

**Comment by sainoba** [comment]
I saw that behavior, but I wasn't sure if it was just my machine.
With the latest update **1.2.5** it should be fixed :)

**Comment by onetrev** [comment]
Yes, fixed! Awesome. I'd love for the cursor to go to the end of the converted rem/px value if possible, but this is awesome as is and much improved. Probably could close this item now as fixed. Thank you so much!
