### ISSUE TITLE
coming again, about Converts

### ISSUE THREAD

**Issue by evanyangg** [sainoba/vscode-px-to-rem#8]
now, in my code like this:
rem(75)
```
.banner {
    height: 75px;
    .image {
        width: 1rem;
     }
}
```
My code may have some weird,  I selected all to convert to rem.
the "height" to 1rem and the "width"  to 75px;
I have to converts one by one,
I think it might be more convenient if there are two hotkeys, 
one converted to rem and one converted to px.
If you convert to rem, you may need to filter out px
I don't know if my thoughts are unreasonable.

**Comment by evanyangg** [comment]
Maybe px needs to be converted to rem is a decimal, rem is converted to the integer required by px

**Comment by sainoba** [comment]
You can actually add the keyboard shortcuts yourself

1. Go to **File > Preferences > Keyboard Shortcuts**
2. Type **px** in the searchbox
3. Assign a keyboard shortcut to the operation you want to perform **px>rem** or **rem>px**

**Comment by evanyangg** [comment]
My fault. thanks a lot!
